map_type: costmap
origin_z: 2.6
z_resolution: 1
z_voxels: 2


robot_base_frame: base_footprint
footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
footprint_padding: 0.01

obstacle_range: 5.0
raytrace_range: 5.5

global_frame: odom
always_send_full_costmap: true

publish_voxel_map: false
transform_tolerance: 0.05
meter_scoring: true

#layer definitions
laser_obstacle:
  observation_sources: scan
  max_obstacle_height: 3.0
  scan: {sensor_frame: base_scan, data_type: LaserScan, topic: /scan, marking: true, clearing: true, min_obstacle_height: -2.0, max_obstacle_height: 3.0}

camera_obstacle:
  observation_sources: camera_scan
  camera_scan: {sensor_frame: camera_link, data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true, min_obstacle_height: -3.0, max_obstacle_height: 3.0}

inflation_global:
  inflation_radius: 0.01

inflation_local:
  inflation_radius: 0.01

cost_scaling_factor: 254
