local_costmap:
  global_frame: odom
  update_frequency: 5.0
  publish_frequency: 5.0
  resolution: 0.05
  width: 10.0
  height: 10.0
  origin_x: -5.0
  origin_y: -5.0
  static_map: false
  rolling_window: true

  plugins:
    - {name: laser_obstacle,      type: "costmap_2d::ObstacleLayer"}
    - {name: camera_obstacle,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_local,     type: "costmap_2d::InflationLayer"}
